
drop table if exists email CASCADE;
create table email (id bigint generated by default as identity, email varchar(255), primary key (id));

drop table if exists author CASCADE;
create table author (id bigint generated by default as identity, name varchar(255), email_id bigint, primary key (id));
alter table author add constraint FK_email foreign key (email_id) references email;

drop table if exists genres CASCADE;
create table genres (id bigint generated by default as identity, genre varchar(255), primary key (id));
